### ISSUE TITLE
Add predominant pollutant to air quality

### ISSUE THREAD

**Issue by jessica-calderon** [jessica-calderon/pollen-tracker#12]
Add air quality api results for predominant air pollutant in air quality section

**Comment by jdcarra** [comment]
if(response.data.aqi <= 50 && response.data.aqi >= 0 ) {
            aqi.css("background-color","green")
            aqi.css ("color", "white")   
        } else if (response.data.aqi >= 51 && response.data.aqi <= 100 ) {
            aqi.css("background-color","yellow")
            aqi.css ("color", "black")   
        } else if (response.data.aqi >= 101 && response.data.aqi <= 150 ) {
            aqi.css("background-color","orange")
            aqi.css ("color", "black")   
        } else if (response.data.aqi >= 151 && response.data.aqi <= 200 ) {
            aqi.css("background-color","red")
            aqi.css ("color", "white")
